# Sonarr - TV Shows management
version: "3.8"

networks:
  media:
    name: media

services:
  radarr:
    image: linuxserver/radarr:preview
    hostname: radarr
    restart: unless-stopped
    networks:
      - media
    volumes:
      - $USERDIR/radarr:/config
      - $MEDIADIR/Downloads:/downloads
      - $MEDIADIR/Movies:/movies
      - "/etc/localtime:/etc/localtime:ro"
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    labels:
      traefik.enable: "true"
      traefik.docker.network: media
      ## HTTP Routers
      traefik.http.routers.radarr.entrypoints: websecure
      traefik.http.routers.radarr.rule: Host(`radarr.$DOMAINNAME`)
      traefik.http.routers.radarr.tls: "true"
    logging:
      driver: "json-file"
      options:
        max-size: "10m"

  bazarr:
    image: linuxserver/bazarr
    volumes:
      - $USERDIR/bazarr:/config
      - $MEDIADIR/Movies:/movies
      - $MEDIADIR/TV:/tv
    restart: unless-stopped
    networks:
      - media
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
      UMASK_SET: 022
    labels:
      traefik.enable: "true"
      traefik.docker.network: media
      ## HTTP Routers
      traefik.http.routers.bazarr.entrypoints: websecure
      traefik.http.routers.bazarr.rule: Host(`bazarr.$DOMAINNAME`)
      traefik.http.routers.bazarr.tls: "true"
    logging:
      driver: "json-file"
      options:
        max-size: "10m"

  sonarr:
    image: linuxserver/sonarr:preview
    restart: unless-stopped
    networks:
      - media
    volumes:
      - $USERDIR/sonarr:/config
      - $MEDIADIR/Downloads:/downloads
      - $MEDIADIR/TV:/tv
      - "/etc/localtime:/etc/localtime:ro"
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    labels:
      traefik.enable: "true"
      traefik.docker.network: media
      ## HTTP Routers
      traefik.http.routers.sonarr.entrypoints: websecure
      traefik.http.routers.sonarr.rule: Host(`sonarr.$DOMAINNAME`)
      traefik.http.routers.sonarr.tls: "true"
    logging:
      driver: "json-file"
      options:
        max-size: "10m"

  lidarr:
    image: linuxserver/lidarr:preview
    restart: unless-stopped
    networks:
      - media
    volumes:
      - $USERDIR/lidarr:/config
      - $MEDIADIR/Downloads:/downloads
      - $MEDIADIR/Music:/music
      - "/etc/localtime:/etc/localtime:ro"
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    labels:
      traefik.enable: "true"
      traefik.docker.network: media
      ## HTTP Routers
      traefik.http.routers.lidarr.entrypoints: websecure
      traefik.http.routers.lidarr.rule: Host(`lidarr.$DOMAINNAME`)
      traefik.http.routers.lidarr.tls: "true"
    logging:
      driver: "json-file"
      options:
        max-size: "10m"

  plex:
    image: plexinc/pms-docker
    restart: unless-stopped
    networks:
      - media
    ports:
      - "$PLEX_PORT:32400/tcp"
      - "3005:3005/tcp"
      - "8324:8324/tcp"
      - "32469:32469/tcp"
      - "1900:1900/udp"
      - "32410:32410/udp"
      - "32412:32412/udp"
      - "32413:32413/udp"
      - "32414:32414/udp"
      - "$PLEX_WEB_TOOLS_PORT:33400"
    volumes:
      - $USERDIR/plexms:/config
      - $MEDIADIR/Downloads:/Downloads
      - $MEDIADIR/TV:/tv
      - $MEDIADIR/Movies:/movies
      - $MEDIADIR/General:/general
      - $MEDIADIR/Music/processed:/Music
      - /dev/shm:/transcode # Offload transcoding to RAM if you have enough RAM
    environment:
      TZ: $TZ
      PUID: $PUID
      PGID: $PGID
      VERSION: docker
    labels:
      com.centurylinklabs.watchtower.enable: "true"
      traefik.enable: "true"
      traefik.docker.network: media
      ## HTTP Routers
      traefik.http.routers.plexms.entrypoints: websecure, websecure-public
      traefik.http.routers.plexms.rule: Host(`plex.$DOMAINNAME`)
      traefik.http.routers.plexms.tls: "true"
      ## HTTP Services
      traefik.http.routers.plexms.service: plexms-svc
      traefik.http.services.plexms-svc.loadbalancer.server.port: 32400
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
