# Sonarr - TV Shows management
version: "3.8"

networks: 
  media:
    name: media


services: 
  radarr:
    image: linuxserver/radarr:preview
    hostname: radarr
    restart: unless-stopped
    networks:
      - media
    volumes:
      - $USERDIR/radarr:/config
      - $MEDIADIR/Downloads:/downloads
      - $MEDIADIR/Movies:/movies
      - "/etc/localtime:/etc/localtime:ro"
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    labels:
      traefik.enable: "true"
      traefik.docker.network: media
      ## HTTP Routers
      traefik.http.routers.radarr.entrypoints: https
      traefik.http.routers.radarr.rule: Host(`radarr.$DOMAINNAME`)
      traefik.http.routers.radarr.tls: "true"
      traefik.http.routers.radarr-api.entrypoints: https
      traefik.http.routers.radarr-api.rule: Host(`radarr.$DOMAINNAME`) && PathPrefix(`/api`)
      traefik.http.routers.radarr-api.tls: "true"
      ## Middlewares
      traefik.http.routers.radarr.middlewares: chain-oauth@file
      traefik.http.routers.radarr-api.middlewares: chain-no-auth@file
      ## HTTP Services
      traefik.http.routers.radarr.service: radarr-svc
      traefik.http.routers.radarr-api.service: radarr-svc
      traefik.http.services.radarr-svc.loadbalancer.server.port: 7878
    logging:
      driver: "json-file"
      options:
        max-size: "10m"

  bazarr:
    image: linuxserver/bazarr
    
    volumes:
      - $USERDIR/bazarr:/config
      - $MEDIADIR/Movies:/movies
      - $MEDIADIR/TV:/tv
    restart: unless-stopped
    networks:
      - media
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
      UMASK_SET: 022
    labels:
      traefik.enable: "true"
      traefik.docker.network: media
      ## HTTP Routers
      traefik.http.routers.bazarr.entrypoints: https
      traefik.http.routers.bazarr.rule: Host(`bazarr.$DOMAINNAME`)
      traefik.http.routers.bazarr.tls: "true"
      ## Middlewares
      traefik.http.routers.bazarr.middlewares: chain-oauth@file
      ## HTTP Services
      traefik.http.routers.bazarr.service: bazarr-svc
      traefik.http.services.bazarr-svc.loadbalancer.server.port: 6767
    logging:
      driver: "json-file"
      options:
        max-size: "10m"

# Set url_base in sonarr settings if using PathPrefix
  sonarr:
    image: linuxserver/sonarr:preview
    restart: unless-stopped
    networks:
      - media
    volumes:
      - $USERDIR/sonarr:/config
      - $MEDIADIR/Downloads:/downloads
      - $MEDIADIR/TV:/tv
      - "/etc/localtime:/etc/localtime:ro"
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    labels:
      traefik.enable: "true"
      traefik.docker.network: media
      ## HTTP Routers
      traefik.http.routers.sonarr.entrypoints: https
      traefik.http.routers.sonarr.rule: Host(`sonarr.$DOMAINNAME`)
      traefik.http.routers.sonarr.tls: "true"
      traefik.http.routers.sonarr-api.entrypoints: https
      traefik.http.routers.sonarr-api.rule: Host(`sonarr.$DOMAINNAME`) && PathPrefix(`/api`)
      traefik.http.routers.sonarr-api.tls: "true"
      ## Middlewares
      traefik.http.routers.sonarr.middlewares: chain-oauth@file
      traefik.http.routers.sonarr-api.middlewares: chain-no-auth@file
      ## HTTP Services
      traefik.http.routers.sonarr.service: sonarr-svc
      traefik.http.routers.sonarr-api.service: sonarr-svc
      traefik.http.services.sonarr-svc.loadbalancer.server.port: 8989
    logging:
      driver: "json-file"
      options:
        max-size: "10m"

  lidarr:
    image: linuxserver/lidarr:preview
    restart: unless-stopped
    networks:
      - media
    volumes:
      - $USERDIR/lidarr:/config
      - $MEDIADIR/Downloads:/downloads
      - $MEDIADIR/Music:/music
      - "/etc/localtime:/etc/localtime:ro"
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    labels:
      traefik.enable: "true"
      traefik.docker.network: media
      ## HTTP Routers
      traefik.http.routers.lidarr.entrypoints: https
      traefik.http.routers.lidarr.rule: Host(`lidarr.$DOMAINNAME`)
      traefik.http.routers.lidarr.tls: "true"
      traefik.http.routers.lidarr-api.entrypoints: https
      traefik.http.routers.lidarr-api.rule: Host(`lidarr.$DOMAINNAME`) && PathPrefix(`/api`)
      traefik.http.routers.lidarr-api.tls: "true"
      ## Middlewares
      traefik.http.routers.lidarr.middlewares: chain-oauth@file
      traefik.http.routers.lidarr-api.middlewares: chain-no-auth@file
      ## HTTP Services
      traefik.http.routers.lidarr.service: lidarr-svc
      traefik.http.routers.lidarr-api.service: lidarr-svc
      traefik.http.services.lidarr-svc.loadbalancer.server.port: 8686
    logging:
      driver: "json-file"
      options:
        max-size: "10m"

# Plex - Media Server
  plex:
    image: linuxserver/plex
    
    hostname: plex
    restart: unless-stopped
    networks:
      - media
    ports:
      - "$PLEX_PORT:32400/tcp"
      - "3005:3005/tcp"
      - "8324:8324/tcp"
      - "32469:32469/tcp"
      - "1900:1900/udp"
      - "32410:32410/udp"
      - "32412:32412/udp"
      - "32413:32413/udp"
      - "32414:32414/udp"
      - "$PLEX_WEB_TOOLS_PORT:33400"
    volumes:
      - $USERDIR/plexms:/config
      - $MEDIADIR/Downloads:/Downloads
      - $MEDIADIR/TV:/tv
      - $MEDIADIR/Movies:/movies
      - $MEDIADIR/Music/processed:/Music
      - /dev/shm:/transcode # Offload transcoding to RAM if you have enough RAM
    environment:
      TZ: $TZ
      PUID: $PUID
      PGID: $PGID
      VERSION: docker
    labels:
      com.centurylinklabs.watchtower.enable: "true"
      traefik.enable: "true"
      traefik.docker.network: media
      ## HTTP Routers
      traefik.http.routers.plexms.entrypoints: https, https-web
      traefik.http.routers.plexms.rule: Host(`plex.$DOMAINNAME`)
      traefik.http.routers.plexms.tls: "true"
      ## Middlewares
      traefik.http.routers.plexms.middlewares: chain-no-auth@file
      ## HTTP Services
      traefik.http.routers.plexms.service: plexms-svc
      traefik.http.services.plexms-svc.loadbalancer.server.port: 32400
    logging:
      driver: "json-file"
      options:
        max-size: "10m"

